version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
#      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
#volumes:
#  db_data:
